package com.ecommerce.user.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Past;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.time.LocalDate;
import java.util.UUID;

/**
 * Request payload for creating a user profile.
 *
 * <p>{@code userId} is optional — when provided (by auth-service during registration)
 * the profile is persisted with that exact UUID so both databases share the same
 * primary key, enabling easy cross-service lookups without a separate mapping table.
 * When omitted (e.g. direct admin calls), a new UUID is generated by the entity.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record UserRequest(
        UUID userId,
        @NotBlank @Email @Size(max = 255) String email,
        @NotBlank @Size(max = 100) String firstName,
        @NotBlank @Size(max = 100) String lastName,
        @Pattern(regexp = "^[0-9+\\-()\\s]{7,20}$", message = "phoneNumber must be a valid phone number")
        String phoneNumber,
        @Past(message = "dateOfBirth must be in the past") LocalDate dateOfBirth,
        @Size(max = 500) String address,
        @Size(max = 1024) String profileImage) {
}
